# Builds and publish docker images
name: Build docker images
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - id: early
        name: Early exit
        run: |
          # Firstly get tag commit message and put it into environment variables
          echo 'GITHUB_TAG_MSG=$(git tag -l --format="%(contents)" $GITHUB_REF_NAME)' >> $GITHUB_ENV
          echo "Tag message:" $GITHUB_TAG_MSG
          if [[ "Build docker images" == "$GITHUB_TAG_MSG"* ]]; then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::failure"
          fi
  build:
    runs-on: ubuntu-latest
    needs: check
    if: !contains(needs.check.outputs.status, 'failure')
    name: Build spark docker image
    steps:
      - name: Test
        run: |
          echo "Tag message:" $GITHUB_TAG_MSG

